# Generated by Django 5.2.6 on 2025-10-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contato_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postagem',
            old_name='autor',
            new_name='owner',
        ),
    ]
