# Generated by Django 5.2.6 on 2025-10-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_autor_postagem_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
