# Generated by Django 5.2.6 on 2025-10-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_postagem_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='texto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
