# Generated by Django 5.2.6 on 2025-10-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contato_texto_alter_contato_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='texto',
            field=models.TextField(blank=True),
        ),
    ]
